Admin_Users_Index:
    pattern: /admin/users
    defaults: { _controller: "AdminModule:User:index"}

Admin_User_Create:
    pattern: /admin/users/create
    defaults: { _controller: "AdminModule:User:create"}

Admin_User_Create_Submit:
    pattern: /admin/users/create-submit
    defaults: { _controller: "AdminModule:User:createSubmit"}
    requirements:
        _method: POST

Admin_User_Edit:
    pattern: /admin/users/edit/{id}
    defaults: { _controller: "AdminModule:User:edit"}

Admin_User_Edit_Submit:
    pattern: /admin/users/edit/{id}
    defaults: { _controller: "AdminModule:User:editSubmit"}
    requirements:
        _method: POST
    
Admin_User_Delete:
    pattern: /admin/users/delete/{id}
    defaults: { _controller: "AdminModule:User:delete"}


       
        
Admin_Index:
    pattern: /admin/
    defaults: { _controller: "AdminModule:Index:index" }
    
Admin_Index2:
    pattern: /admin
    defaults: { _controller: "AdminModule:Index:index" }



Admin_Lugares_Index:
    pattern: /admin/lugares/
    defaults: { _controller: "AdminModule:Lugar:index" }

Admin_Lugares_Create:
    pattern: /admin/lugares/create
    defaults: { _controller: "AdminModule:Lugar:create" }

Admin_Lugares_Edit:
    pattern: /admin/lugares/edit/{id}
    defaults: { _controller: "AdminModule:Lugar:edit" }

Admin_Lugares_Delete:
    pattern: /admin/lugares/delete/{id}
    defaults: { _controller: "AdminModule:Lugar:delete" }

Admin_Personas_Index:
    pattern: /admin/personas/
    defaults: { _controller: "AdminModule:Persona:index" }

Admin_Personas_Create:
    pattern: /admin/personas/create
    defaults: { _controller: "AdminModule:Persona:create" }

Admin_Personas_Edit:
    pattern: /admin/personas/edit/{id}
    defaults: { _controller: "AdminModule:Persona:edit" }

Admin_Personas_Delete:
    pattern: /admin/personas/delete/{id}
    defaults: { _controller: "AdminModule:Persona:delete" }